GET http://localhost:3003/character?name=o&orderType=DESC

###

PUT http://localhost:3003/character
Content-Type: application/json

{
    "name": "Pamela",
    "gender":"FEMALE",
    "description": "Pamela menina bonita"
}

###

DELETE  http://localhost:3003/character/3